export const GET_CITYLIST="GET_CITYLIST";
export const CHOOSE_CITYLIST="CHOOSE_CITYLIST";
export const GET_NOWPLAYING="GET_NOWPLAYING";
export const GET_COMINGLAYING="GET_COMINGLAYING";
export const GET_SEARCHLIST="GET_SEARCHLIST";
export const GET_CINEMALIST="GET_CINEMALIST";
export const GET_LOCATION="GET_LOCATION";
export const GET_MOVIEDETAIL="GET_MOVIEDETAIL";
